### ISSUE TITLE
Im facing the HTTP Error 404: Not Found for few movies any fix ?

### ISSUE THREAD

**Issue by gyanadeep** [ajayrfhp/subtitle-downloader#3]
Traceback (most recent call last):
  File "/usr/local/bin/subtitle-fetcher", line 9, in <module>
    load_entry_point('subtitle-fetcher==0.1.0', 'console_scripts', 'subtitle-fetcher')()
  File "/Library/Python/2.7/site-packages/subtitle_downloader/subtitle.py", line 34, in main
    res = urllib2.urlopen(req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

Ps: great fan of your work if you can add scanning a folder and download subs for every movie feature ill be grateful

Thanks

**Comment by nateshmbhat** [comment]
I have included all the features for **bulk downloading** of subtitles for **entire folders** ( can also contain any inlevel number of folders and still work )  and have added support for multiple languages .  U can check it out here :- https://github.com/nateshmbhat/Subtitles_grabber
